export interface Country {
  label: string;
  value: string;
}

const countriesKo: Country[] = [
  { label: '미국 (+1)', value: '미국 (+1)' },
  { label: '캐나다 (+1)', value: '캐나다 (+1)' },
  { label: '러시아 (+7)', value: '러시아 (+7)' },
  { label: '카자흐스탄 (+7)', value: '카자흐스탄 (+7)' },
  { label: '이집트 (+20)', value: '이집트 (+20)' },
  { label: '남아프리카공화국 (+27)', value: '남아프리카공화국 (+27)' },
  { label: '그리스 (+30)', value: '그리스 (+30)' },
  { label: '네덜란드 (+31)', value: '네덜란드 (+31)' },
  { label: '벨기에 (+32)', value: '벨기에 (+32)' },
  { label: '프랑스 (+33)', value: '프랑스 (+33)' },
  { label: '스페인 (+34)', value: '스페인 (+34)' },
  { label: '헝가리 (+36)', value: '헝가리 (+36)' },
  { label: '이탈리아 (+39)', value: '이탈리아 (+39)' },
  { label: '루마니아 (+40)', value: '루마니아 (+40)' },
  { label: '스위스 (+41)', value: '스위스 (+41)' },
  { label: '오스트리아 (+43)', value: '오스트리아 (+43)' },
  { label: '영국 (+44)', value: '영국 (+44)' },
  { label: '덴마크 (+45)', value: '덴마크 (+45)' },
  { label: '스웨덴 (+46)', value: '스웨덴 (+46)' },
  { label: '노르웨이 (+47)', value: '노르웨이 (+47)' },
  { label: '폴란드 (+48)', value: '폴란드 (+48)' },
  { label: '독일 (+49)', value: '독일 (+49)' },
  { label: '페루 (+51)', value: '페루 (+51)' },
  { label: '멕시코 (+52)', value: '멕시코 (+52)' },
  { label: '쿠바 (+53)', value: '쿠바 (+53)' },
  { label: '아르헨티나 (+54)', value: '아르헨티나 (+54)' },
  { label: '브라질 (+55)', value: '브라질 (+55)' },
  { label: '칠레 (+56)', value: '칠레 (+56)' },
  { label: '콜롬비아 (+57)', value: '콜롬비아 (+57)' },
  { label: '베네수엘라 (+58)', value: '베네수엘라 (+58)' },
  { label: '말레이시아 (+60)', value: '말레이시아 (+60)' },
  { label: '호주 (+61)', value: '호주 (+61)' },
  { label: '인도네시아 (+62)', value: '인도네시아 (+62)' },
  { label: '필리핀 (+63)', value: '필리핀 (+63)' },
  { label: '뉴질랜드 (+64)', value: '뉴질랜드 (+64)' },
  { label: '싱가포르 (+65)', value: '싱가포르 (+65)' },
  { label: '태국 (+66)', value: '태국 (+66)' },
  { label: '일본 (+81)', value: '일본 (+81)' },
  { label: '대한민국 (+82)', value: '대한민국 (+82)' },
  { label: '베트남 (+84)', value: '베트남 (+84)' },
  { label: '중국 (+86)', value: '중국 (+86)' },
  { label: '터키 (+90)', value: '터키 (+90)' },
  { label: '인도 (+91)', value: '인도 (+91)' },
  { label: '파키스탄 (+92)', value: '파키스탄 (+92)' },
  { label: '아프가니스탄 (+93)', value: '아프가니스탄 (+93)' },
  { label: '스리랑카 (+94)', value: '스리랑카 (+94)' },
  { label: '미얀마 (+95)', value: '미얀마 (+95)' },
  { label: '이란 (+98)', value: '이란 (+98)' },
  { label: '남수단 (+211)', value: '남수단 (+211)' },
  { label: '모로코 (+212)', value: '모로코 (+212)' },
  { label: '알제리 (+213)', value: '알제리 (+213)' },
  { label: '튀니지 (+216)', value: '튀니지 (+216)' },
  { label: '리비아 (+218)', value: '리비아 (+218)' },
  { label: '감비아 (+220)', value: '감비아 (+220)' },
  { label: '세네갈 (+221)', value: '세네갈 (+221)' },
  { label: '모리타니 (+222)', value: '모리타니 (+222)' },
  { label: '말리 (+223)', value: '말리 (+223)' },
  { label: '기니 (+224)', value: '기니 (+224)' },
  { label: '코트디부아르 (+225)', value: '코트디부아르 (+225)' },
  { label: '부르키나파소 (+226)', value: '부르키나파소 (+226)' },
  { label: '니제르 (+227)', value: '니제르 (+227)' },
  { label: '토고 (+228)', value: '토고 (+228)' },
  { label: '모리셔스 (+230)', value: '모리셔스 (+230)' },
  { label: '라이베리아 (+231)', value: '라이베리아 (+231)' },
  { label: '가나 (+233)', value: '가나 (+233)' },
  { label: '나이지리아 (+234)', value: '나이지리아 (+234)' },
  { label: '차드 (+235)', value: '차드 (+235)' },
  { label: '중앙아프리카공화국 (+236)', value: '중앙아프리카공화국 (+236)' },
  { label: '카메룬 (+237)', value: '카메룬 (+237)' },
  { label: '카보베르데 (+238)', value: '카보베르데 (+238)' },
  { label: '상투메 프린시페 (+239)', value: '상투메 프린시페 (+239)' },
  { label: '적도기니 (+240)', value: '적도기니 (+240)' },
  { label: '가봉 (+241)', value: '가봉 (+241)' },
  { label: '콩고공화국 (+242)', value: '콩고공화국 (+242)' },
  { label: '앙골라 (+244)', value: '앙골라 (+244)' },
  { label: '기니비사우 (+245)', value: '기니비사우 (+245)' },
  { label: '세이셸 (+248)', value: '세이셸 (+248)' },
  { label: '수단 (+249)', value: '수단 (+249)' },
  { label: '르완다 (+250)', value: '르완다 (+250)' },
  { label: '에티오피아 (+251)', value: '에티오피아 (+251)' },
  { label: '소말리아 (+252)', value: '소말리아 (+252)' },
  { label: '지부티 (+253)', value: '지부티 (+253)' },
  { label: '케냐 (+254)', value: '케냐 (+254)' },
  { label: '탄자니아 (+255)', value: '탄자니아 (+255)' },
  { label: '우간다 (+256)', value: '우간다 (+256)' },
  { label: '부룬디 (+257)', value: '부룬디 (+257)' },
  { label: '모잠비크 (+258)', value: '모잠비크 (+258)' },
  { label: '잠비아 (+260)', value: '잠비아 (+260)' },
  { label: '마다가스카르 (+261)', value: '마다가스카르 (+261)' },
  { label: '짐바브웨 (+263)', value: '짐바브웨 (+263)' },
  { label: '나미비아 (+264)', value: '나미비아 (+264)' },
  { label: '말라위 (+265)', value: '말라위 (+265)' },
  { label: '레소토 (+266)', value: '레소토 (+266)' },
  { label: '보츠와나 (+267)', value: '보츠와나 (+267)' },
  { label: '에스와티니 (+268)', value: '에스와티니 (+268)' },
  { label: '코모로 (+269)', value: '코모로 (+269)' },
  { label: '에리트레아 (+291)', value: '에리트레아 (+291)' },
  { label: '그린란드 (+299)', value: '그린란드 (+299)' },
  { label: '포르투갈 (+351)', value: '포르투갈 (+351)' },
  { label: '룩셈부르크 (+352)', value: '룩셈부르크 (+352)' },
  { label: '아일랜드 (+353)', value: '아일랜드 (+353)' },
  { label: '아이슬란드 (+354)', value: '아이슬란드 (+354)' },
  { label: '알바니아 (+355)', value: '알바니아 (+355)' },
  { label: '키프로스 (+357)', value: '키프로스 (+357)' },
  { label: '핀란드 (+358)', value: '핀란드 (+358)' },
  { label: '불가리아 (+359)', value: '불가리아 (+359)' },
  { label: '리투아니아 (+370)', value: '리투아니아 (+370)' },
  { label: '라트비아 (+371)', value: '라트비아 (+371)' },
  { label: '에스토니아 (+372)', value: '에스토니아 (+372)' },
  { label: '아르메니아 (+374)', value: '아르메니아 (+374)' },
  { label: '벨라루스 (+375)', value: '벨라루스 (+375)' },
  { label: '안도라 (+376)', value: '안도라 (+376)' },
  { label: '모나코 (+377)', value: '모나코 (+377)' },
  { label: '산마리노 (+378)', value: '산마리노 (+378)' },
  { label: '우크라이나 (+380)', value: '우크라이나 (+380)' },
  { label: '세르비아 (+381)', value: '세르비아 (+381)' },
  { label: '몬테네그로 (+382)', value: '몬테네그로 (+382)' },
  { label: '크로아티아 (+385)', value: '크로아티아 (+385)' },
  { label: '슬로베니아 (+386)', value: '슬로베니아 (+386)' },
  {
    label: '보스니아 헤르체고비나 (+387)',
    value: '보스니아 헤르체고비나 (+387)',
  },
  { label: '북마케도니아 (+389)', value: '북마케도니아 (+389)' },
  { label: '체코 (+420)', value: '체코 (+420)' },
  { label: '슬로바키아 (+421)', value: '슬로바키아 (+421)' },
  { label: '리히텐슈타인 (+423)', value: '리히텐슈타인 (+423)' },
  { label: '벨리즈 (+501)', value: '벨리즈 (+501)' },
  { label: '과테말라 (+502)', value: '과테말라 (+502)' },
  { label: '엘살바도르 (+503)', value: '엘살바도르 (+503)' },
  { label: '온두라스 (+504)', value: '온두라스 (+504)' },
  { label: '니카라과 (+505)', value: '니카라과 (+505)' },
  { label: '코스타리카 (+506)', value: '코스타리카 (+506)' },
  { label: '파나마 (+507)', value: '파나마 (+507)' },
  { label: '과들루프 (+590)', value: '과들루프 (+590)' },
  { label: '볼리비아 (+591)', value: '볼리비아 (+591)' },
  { label: '가이아나 (+592)', value: '가이아나 (+592)' },
  { label: '에콰도르 (+593)', value: '에콰도르 (+593)' },
  { label: '파라과이 (+595)', value: '파라과이 (+595)' },
  { label: '수리남 (+597)', value: '수리남 (+597)' },
  { label: '우루과이 (+598)', value: '우루과이 (+598)' },
  { label: '동티모르 (+670)', value: '동티모르 (+670)' },
  { label: '브루나이 (+673)', value: '브루나이 (+673)' },
  { label: '나우루 (+674)', value: '나우루 (+674)' },
  { label: '파푸아뉴기니 (+675)', value: '파푸아뉴기니 (+675)' },
  { label: '통가 (+676)', value: '통가 (+676)' },
  { label: '솔로몬제도 (+677)', value: '솔로몬제도 (+677)' },
  { label: '바누아투 (+678)', value: '바누아투 (+678)' },
  { label: '피지 (+679)', value: '피지 (+679)' },
  { label: '팔라우 (+680)', value: '팔라우 (+680)' },
  { label: '니우에 (+683)', value: '니우에 (+683)' },
  { label: '사모아 (+685)', value: '사모아 (+685)' },
  { label: '키리바시 (+686)', value: '키리바시 (+686)' },
  { label: '투발루 (+688)', value: '투발루 (+688)' },
  { label: '마셜제도 (+692)', value: '마셜제도 (+692)' },
  { label: '마카오 (+853)', value: '마카오 (+853)' },
  { label: '캄보디아 (+855)', value: '캄보디아 (+855)' },
  { label: '라오스 (+856)', value: '라오스 (+856)' },
  { label: '방글라데시 (+880)', value: '방글라데시 (+880)' },
  { label: '레바논 (+961)', value: '레바논 (+961)' },
  { label: '시리아 (+963)', value: '시리아 (+963)' },
  { label: '이라크 (+964)', value: '이라크 (+964)' },
  { label: '쿠웨이트 (+965)', value: '쿠웨이트 (+965)' },
  { label: '사우디아라비아 (+966)', value: '사우디아라비아 (+966)' },
  { label: '예멘 (+967)', value: '예멘 (+967)' },
  { label: '오만 (+968)', value: '오만 (+968)' },
  { label: '이스라엘 (+972)', value: '이스라엘 (+972)' },
  { label: '바레인 (+973)', value: '바레인 (+973)' },
  { label: '카타르 (+974)', value: '카타르 (+974)' },
  { label: '부탄 (+975)', value: '부탄 (+975)' },
  { label: '몽골 (+976)', value: '몽골 (+976)' },
  { label: '네팔 (+977)', value: '네팔 (+977)' },
  { label: '타지키스탄 (+992)', value: '타지키스탄 (+992)' },
  { label: '투르크메니스탄 (+993)', value: '투르크메니스탄 (+993)' },
  { label: '아제르바이잔 (+994)', value: '아제르바이잔 (+994)' },
  { label: '조지아 (+995)', value: '조지아 (+995)' },
  { label: '키르기스스탄 (+996)', value: '키르기스스탄 (+996)' },
  { label: '우즈베키스탄 (+998)', value: '우즈베키스탄 (+998)' },
];

const koToEn: Record<string, string> = {
  미국: 'United States',
  캐나다: 'Canada',
  러시아: 'Russia',
  카자흐스탄: 'Kazakhstan',
  이집트: 'Egypt',
  남아프리카공화국: 'South Africa',
  그리스: 'Greece',
  네덜란드: 'Netherlands',
  벨기에: 'Belgium',
  프랑스: 'France',
  스페인: 'Spain',
  헝가리: 'Hungary',
  이탈리아: 'Italy',
  루마니아: 'Romania',
  스위스: 'Switzerland',
  오스트리아: 'Austria',
  영국: 'United Kingdom',
  덴마크: 'Denmark',
  스웨덴: 'Sweden',
  노르웨이: 'Norway',
  폴란드: 'Poland',
  독일: 'Germany',
  페루: 'Peru',
  멕시코: 'Mexico',
  쿠바: 'Cuba',
  아르헨티나: 'Argentina',
  브라질: 'Brazil',
  칠레: 'Chile',
  콜롬비아: 'Colombia',
  베네수엘라: 'Venezuela',
  말레이시아: 'Malaysia',
  호주: 'Australia',
  인도네시아: 'Indonesia',
  필리핀: 'Philippines',
  뉴질랜드: 'New Zealand',
  싱가포르: 'Singapore',
  태국: 'Thailand',
  일본: 'Japan',
  대한민국: 'South Korea',
  베트남: 'Vietnam',
  중국: 'China',
  터키: 'Turkey',
  인도: 'India',
  파키스탄: 'Pakistan',
  아프가니스탄: 'Afghanistan',
  스리랑카: 'Sri Lanka',
  미얀마: 'Myanmar',
  이란: 'Iran',
  모로코: 'Morocco',
  알제리: 'Algeria',
  튀니지: 'Tunisia',
  리비아: 'Libya',
  세네갈: 'Senegal',
  나이지리아: 'Nigeria',
  케냐: 'Kenya',
  탄자니아: 'Tanzania',
  우간다: 'Uganda',
  에티오피아: 'Ethiopia',
  소말리아: 'Somalia',
  포르투갈: 'Portugal',
  룩셈부르크: 'Luxembourg',
  아일랜드: 'Ireland',
  아이슬란드: 'Iceland',
  알바니아: 'Albania',
  키프로스: 'Cyprus',
  핀란드: 'Finland',
  불가리아: 'Bulgaria',
  리투아니아: 'Lithuania',
  라트비아: 'Latvia',
  에스토니아: 'Estonia',
  아르메니아: 'Armenia',
  벨라루스: 'Belarus',
  안도라: 'Andorra',
  모나코: 'Monaco',
  산마리노: 'San Marino',
  우크라이나: 'Ukraine',
  세르비아: 'Serbia',
  몬테네그로: 'Montenegro',
  크로아티아: 'Croatia',
  슬로베니아: 'Slovenia',
  '보스니아 헤르체고비나': 'Bosnia and Herzegovina',
  북마케도니아: 'North Macedonia',
  체코: 'Czech Republic',
  슬로바키아: 'Slovakia',
  리히텐슈타인: 'Liechtenstein',
  벨리즈: 'Belize',
  과테말라: 'Guatemala',
  엘살바도르: 'El Salvador',
  온두라스: 'Honduras',
  니카라과: 'Nicaragua',
  코스타리카: 'Costa Rica',
  파나마: 'Panama',
  볼리비아: 'Bolivia',
  가이아나: 'Guyana',
  에콰도르: 'Ecuador',
  파라과이: 'Paraguay',
  수리남: 'Suriname',
  우루과이: 'Uruguay',
  동티모르: 'Timor-Leste',
  브루나이: 'Brunei',
  나우루: 'Nauru',
  파푸아뉴기니: 'Papua New Guinea',
  통가: 'Tonga',
  솔로몬제도: 'Solomon Islands',
  바누아투: 'Vanuatu',
  피지: 'Fiji',
  팔라우: 'Palau',
  니우에: 'Niue',
  사모아: 'Samoa',
  키리바시: 'Kiribati',
  투발루: 'Tuvalu',
  마셜제도: 'Marshall Islands',
  마카오: 'Macao',
  캄보디아: 'Cambodia',
  라오스: 'Laos',
  방글라데시: 'Bangladesh',
  레바논: 'Lebanon',
  시리아: 'Syria',
  이라크: 'Iraq',
  쿠웨이트: 'Kuwait',
  사우디아라비아: 'Saudi Arabia',
  예멘: 'Yemen',
  오만: 'Oman',
  이스라엘: 'Israel',
  바레인: 'Bahrain',
  카타르: 'Qatar',
  부탄: 'Bhutan',
  몽골: 'Mongolia',
  네팔: 'Nepal',
  타지키스탄: 'Tajikistan',
  투르크메니스탄: 'Turkmenistan',
  아제르바이잔: 'Azerbaijan',
  조지아: 'Georgia',
  키르기스스탄: 'Kyrgyzstan',
  우즈베키스탄: 'Uzbekistan',
  남수단: 'South Sudan',
  모리셔스: 'Mauritius',
  라이베리아: 'Liberia',
  가나: 'Ghana',
  차드: 'Chad',
  중앙아프리카공화국: 'Central African Republic',
  카메룬: 'Cameroon',
  카보베르데: 'Cape Verde',
  '상투메 프린시페': 'Sao Tome and Principe',
  적도기니: 'Equatorial Guinea',
  가봉: 'Gabon',
  콩고공화국: 'Republic of the Congo',
  앙골라: 'Angola',
  기니비사우: 'Guinea-Bissau',
  세이셸: 'Seychelles',
  수단: 'Sudan',
  르완다: 'Rwanda',
  모잠비크: 'Mozambique',
  잠비아: 'Zambia',
  마다가스카르: 'Madagascar',
  짐바브웨: 'Zimbabwe',
  나미비아: 'Namibia',
  말라위: 'Malawi',
  레소토: 'Lesotho',
  보츠와나: 'Botswana',
  에스와티니: 'Eswatini',
  코모로: 'Comoros',
  에리트레아: 'Eritrea',
  그린란드: 'Greenland',
};

const toEnLabel = (koLabel: string): string => {
  const match = koLabel.match(/^(.*)\s*(\(\+\d+\))$/);
  if (!match) return koLabel;
  const nameKo = match[1].trim();
  const code = match[2];
  const nameEn = koToEn[nameKo] ?? nameKo;
  return `${nameEn} ${code}`;
};

export const getCountries = (language: string): Country[] => {
  if (language?.startsWith('en')) {
    return countriesKo.map((c) => ({
      label: toEnLabel(c.label),
      value: toEnLabel(c.value),
    }));
  }
  return countriesKo;
};

// Backward compatibility default export
export const countries: Country[] = countriesKo;
